name: env
channels:
  - defaults
dependencies:
  - _libgcc_mutex
  - _pytorch_select
  - blas
  - ca-certificates
  - ld_impl_linux-64
  - libgfortran4
  - libstdcxx-ng
  - llvm-openmp
  - pandoc
  - _openmp_mutex
  - libgfortran-ng
  - libgcc-ng
  - mkl
  - c-ares
  - cudatoolkit
  - icu
  - libffi
  - libsodium
  - ncurses
  - ninja
  - openssl
  - xz
  - zlib
  - cudnn
  - hdf5
  - libpng
  - libprotobuf
  - readline
  - tk
  - zeromq
  - freetype
  - sqlite
  - python=3.7
  - async_generator
  - attrs
  - backcall
  - backports
  - cached-property
  - certifi
  - dataclasses
  - decorator
  - defusedxml
  - entrypoints
  - ipython_genutils
  - munkres
  - nest-asyncio
  - pandocfilters
  - parso
  - pickleshare
  - prometheus_client
  - ptyprocess
  - pycparser
  - pyparsing
  - python_abi
  - pytz
  - send2trash
  - six
  - testpath
  - threadpoolctl
  - tqdm
  - typing_extensions
  - webencodings
  - wheel
  - zipp
  - absl-py
  - cffi
  - cycler
  - importlib-metadata
  - jedi
  - kiwisolver
  - markupsafe
  - mistune
  - mkl-service
  - packaging
  - pexpect
  - pyrsistent
  - python-dateutil
  - pyzmq
  - setuptools
  - tornado
  - traitlets
  - werkzeug
  - argon2-cffi
  - backports.functools_lru_cache
  - bleach
  - grpcio
  - jinja2
  - joblib
  - jsonschema
  - jupyter_core
  - markdown
  - matplotlib-inline
  - networkx
  - numpy-base
  - pip
  - protobuf
  - pygments
  - terminado
  - jupyter_client
  - jupyterlab_pygments
  - mkl_random
  - nbformat
  - wcwidth
  - nbclient
  - prompt-toolkit
  - ipython
  - nbconvert
  - ipykernel
  - notebook
  - matplotlib
  - matplotlib-base
  - pandas
  - tensorboard
  - h5py
  - mkl_fft
  - numpy
  - pytorch
  - scipy
  - scikit-learn
  - snorkel
  - neurokit2
  - pywavelets
  - bokeh